var A=45
if(A ==45){
    console.log("yes");           //if else statements
}else{
    console.log("no");
}

var s="hello good morning"
if(s !="hi"){                      //if statements
    console.log("different");
}
   let hr=12
   if(hr<10){
    console.log("good morning");          //else if
   }else if (hr>10 && hr<14){
        console.log("good day");
   }else{
    console.log("good evening");
   }

         let amount=500
         switch(amount){
            case 1000:console.log("minimum balance is maintained");
            break;
            case 2000
            :console.log("5% interest is credited");
            break;
            default
            :console.log("insufficient balance");
            break;
         }



    

         